# Generated by Django 4.2.5 on 2023-10-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="", upload_to="intruder_image/%Y/%m/%d/"),
            preserve_default=False,
        ),
    ]
